/*
    Create a PL/SQL procedure that takes two input parameters
    (employee_id and salary_increase) and updates the salary
    of an employee with the given employee_id by applying the
    salary_increase.
*/

 -- Step 1, make table and values. commit changes
CREATE TABLE employee (
                          employee_id number generated by default as identity,
                          first_name varchar(50),
                          last_name varchar(50),
                          salary number (6,2)
);

insert into employee (first_name, last_name, salary) values ('Eric', 'Erwin', 2345.29);
insert into employee (first_name, last_name, salary) values ('Sven', 'Svenson', 5558.29);

commit;

 -- Step 2, create the procedure and commit it
CREATE OR REPLACE PROCEDURE update_salary (
    employee_id IN NUMBER,
    salary_increase IN NUMBER
)IS
BEGIN
UPDATE employee
SET salary = salary + salary_increase
WHERE employee_id = employee_id;
COMMIT;
EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

commit;

 -- Step 3, run the command
exec update_salary(1, 25.23);
