INSERT INTO DEPARTMENT VALUES (1, 'HR');
INSERT INTO DEPARTMENT VALUES (2, 'DEV OPS');
INSERT INTO DEPARTMENT VALUES (3, 'DBA');
INSERT INTO DEPARTMENT VALUES (4, 'SYS ADMIN');
INSERT INTO DEPARTMENT VALUES (5, 'ENGINEERS');
INSERT INTO DEPARTMENT VALUES (6, 'MANAGEMENT');

commit;
