/*

 Step One:
    Create a table named employees to store employee information. Include columns such as employee_id,
    first_name, last_name, hire_date, job_id, salary, and department_id.

    Create a table named job_history to store historical job information for employees. Include columns
    such as employee_id, job_id, start_date, and end_date.

 */

CREATE TABLE employee (
    employee_id number generated by default as identity primary key,
    first_name varchar2(100),
    last_name varchar2(100),
    hire_date date,
    job_id varchar(100),
    department_id number
);

CREATE TABLE job_history (
    employee_id number,
    job_id varchar(100),
    start_date date,
    end_date date
);

-- Insert dummy data into the employee table
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('John', 'Doe', TO_DATE('2022-01-10', 'YYYY-MM-DD'), 'Manager', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Alice', 'Smith', TO_DATE('2021-03-15', 'YYYY-MM-DD'), 'Developer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Bob', 'Johnson', TO_DATE('2021-05-20', 'YYYY-MM-DD'), 'Analyst', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Emily', 'Davis', TO_DATE('2022-02-18', 'YYYY-MM-DD'), 'Designer', 3);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('David', 'Lee', TO_DATE('2022-06-05', 'YYYY-MM-DD'), 'Engineer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Sarah', 'Brown', TO_DATE('2022-04-12', 'YYYY-MM-DD'), 'Manager', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Michael', 'Wilson', TO_DATE('2022-03-25', 'YYYY-MM-DD'), 'Developer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Linda', 'Anderson', TO_DATE('2021-07-30', 'YYYY-MM-DD'), 'Analyst', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Chris', 'Martinez', TO_DATE('2021-09-02', 'YYYY-MM-DD'), 'Designer', 3);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Jennifer', 'Garcia', TO_DATE('2022-05-08', 'YYYY-MM-DD'), 'Engineer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Daniel', 'Harris', TO_DATE('2022-03-10', 'YYYY-MM-DD'), 'Manager', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Mary', 'Taylor', TO_DATE('2022-01-05', 'YYYY-MM-DD'), 'Developer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Kevin', 'Clark', TO_DATE('2021-08-14', 'YYYY-MM-DD'), 'Analyst', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Laura', 'Lewis', TO_DATE('2021-06-22', 'YYYY-MM-DD'), 'Designer', 3);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Thomas', 'Hall', TO_DATE('2022-02-28', 'YYYY-MM-DD'), 'Engineer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Nancy', 'Young', TO_DATE('2022-04-01', 'YYYY-MM-DD'), 'Manager', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Paul', 'Walker', TO_DATE('2021-09-28', 'YYYY-MM-DD'), 'Developer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Kimberly', 'Wright', TO_DATE('2021-10-11', 'YYYY-MM-DD'), 'Analyst', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Richard', 'Green', TO_DATE('2022-07-03', 'YYYY-MM-DD'), 'Designer', 3);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Susan', 'Evans', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 'Engineer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('William', 'Hill', TO_DATE('2022-06-10', 'YYYY-MM-DD'), 'Manager', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Karen', 'Adams', TO_DATE('2021-12-04', 'YYYY-MM-DD'), 'Developer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Edward', 'Perez', TO_DATE('2021-11-19', 'YYYY-MM-DD'), 'Analyst', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Patricia', 'Turner', TO_DATE('2022-03-03', 'YYYY-MM-DD'), 'Designer', 3);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Steven', 'Baker', TO_DATE('2022-02-14', 'YYYY-MM-DD'), 'Engineer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Elizabeth', 'White', TO_DATE('2022-05-22', 'YYYY-MM-DD'), 'Manager', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('George', 'Collins', TO_DATE('2021-10-31', 'YYYY-MM-DD'), 'Developer', 2);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Margaret', 'Gonzalez', TO_DATE('2021-08-08', 'YYYY-MM-DD'), 'Analyst', 1);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Joseph', 'Mitchell', TO_DATE('2022-01-28', 'YYYY-MM-DD'), 'Designer', 3);
INSERT INTO employee (first_name, last_name, hire_date, job_id, department_id)
VALUES
    ('Dorothy', 'Thompson', TO_DATE('2022-04-20', 'YYYY-MM-DD'), 'Engineer', 2);

INSERT INTO job_history (employee_id, job_id, start_date, end_date)
VALUES (1, 'Manager', TO_DATE('2022-01-10', 'YYYY-MM-DD'), TO_DATE('2022-06-30', 'YYYY-MM-DD'));

INSERT INTO job_history (employee_id, job_id, start_date, end_date)
VALUES (2, 'Developer', TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2022-01-15', 'YYYY-MM-DD'));

INSERT INTO job_history (employee_id, job_id, start_date, end_date)
VALUES (3, 'Analyst', TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2022-01-15', 'YYYY-MM-DD'));

INSERT INTO job_history (employee_id, job_id, start_date, end_date)
VALUES (4, 'Designer', TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2022-01-15', 'YYYY-MM-DD'));

INSERT INTO job_history (employee_id, job_id, start_date, end_date)
VALUES (5, 'Engineer', TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2022-01-15', 'YYYY-MM-DD'));


